import { AttractionItem } from '../../src/types.js';

export const CURATED_LANDMARKS: AttractionItem[] = [
  // 51. INDORE - Rajwada Palace
  {
    id: 'attr-rajwada-palace-indore',
    name: 'Rajwada Palace, Indore',
    category: 'Seven-Story Holkar Royal Palace',
    lat: 22.7186,
    lng: 75.8550,
    address: 'Rajwada Circle, MG Road, Indore, Madhya Pradesh 452002',
    shortDescription: 'Historic 7-story palace built by the Holkars in 1766, blending Maratha, Mughal, and French architecture with wooden balconies and stone archways.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=22.7186,75.8550',
    ticketPrice: {
      amount: 20,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 20 for Indians, INR 250 for foreign tourists; Evening Sound & Light show INR 100',
    },
    openingHours: '10:00 - 17:00 (Sound & Light show 19:30 - 20:30; closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 400,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Late afternoon followed by night food walk at Sarafa Bazaar',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-rp-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Rajwada_Indore.jpg/1280px-Rajwada_Indore.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Rajwada_Indore.jpg/400px-Rajwada_Indore.jpg',
        title: 'Front facade of Rajwada Palace Indore',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Madhya Pradesh Tourism',
      }
    ],
    source: 'Madhya Pradesh Tourism Development Corporation',
    lastUpdated: new Date().toISOString(),
  },

  // 52. INDORE - Lal Bagh Palace
  {
    id: 'attr-lal-bagh-palace-indore',
    name: 'Lal Bagh Palace, Indore',
    category: 'European Neoclassical Royal Estate',
    lat: 22.6975,
    lng: 75.8450,
    address: 'Nai Duniya, Revenue Colony, Indore, Madhya Pradesh 452007',
    shortDescription: 'Opulent palace built between 1886 and 1921 by Tukojirao Holkar II, featuring gates modeled after Buckingham Palace and authentic Versailles-style interiors.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=22.6975,75.8450',
    ticketPrice: {
      amount: 20,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 20 for Indians, INR 250 for foreign tourists',
    },
    openingHours: '10:00 - 17:00 (Closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 75,
      walkingDistanceMeters: 600,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or early afternoon',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'low',
    },
    photos: [
      {
        id: 'wm-lbp-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Lal_Bagh_Palace%2C_Indore.jpg/1280px-Lal_Bagh_Palace%2C_Indore.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Lal_Bagh_Palace%2C_Indore.jpg/400px-Lal_Bagh_Palace%2C_Indore.jpg',
        title: 'Grand entrance gates and facade of Lal Bagh Palace',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Madhya Pradesh Tourism',
      }
    ],
    source: 'Madhya Pradesh Tourism Development Corporation',
    lastUpdated: new Date().toISOString(),
  },

  // 53. BENGALURU - Vidhana Soudha
  {
    id: 'attr-vidhana-soudha-bengaluru',
    name: 'Vidhana Soudha & Cubbon Park',
    category: 'Neo-Dravidian State Capitol & Urban Park',
    lat: 12.9797,
    lng: 77.5907,
    address: 'Ambedkar Bheedhi, Sampangi Rama Nagara, Bengaluru, Karnataka 560001',
    shortDescription: "Seat of Karnataka's legislature, constructed in majestic Neo-Dravidian granite style in 1956, facing the 300-acre lush botanical gardens of Cubbon Park.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=12.9797,77.5907',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free exterior viewing and public park access' },
    openingHours: 'Cubbon Park 06:00 - 18:00 Daily; Vidhana Soudha exterior illuminated Sundays & holidays 19:00 - 20:30',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 750,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Sunday evening for illuminated granite facade or morning walk in Cubbon Park',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-vs-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Vidhana_Soudha%2C_Bangalore%2C_India.jpg/1280px-Vidhana_Soudha%2C_Bangalore%2C_India.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Vidhana_Soudha%2C_Bangalore%2C_India.jpg/400px-Vidhana_Soudha%2C_Bangalore%2C_India.jpg',
        title: 'Grand Neo-Dravidian granite facade of Vidhana Soudha Bangalore',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 3.0',
        source: 'Karnataka Tourism',
      }
    ],
    source: 'Karnataka State Tourism Development',
    lastUpdated: new Date().toISOString(),
  },

  // 55. MUMBAI - Bandra-Worli Sea Link
  {
    id: 'attr-bandra-worli-sea-link',
    name: 'Bandra-Worli Sea Link (Rajiv Gandhi Sea Link)',
    category: 'Modern Cable-Stayed Oceanic Bridge Landmark',
    lat: 19.0365,
    lng: 72.8172,
    address: 'Mahim Bay, Bandra West to Worli, Mumbai, Maharashtra 400050',
    shortDescription: '5.6 km 8-lane cable-stayed bridge spanning Mahim Bay in the Arabian Sea, an architectural icon of modern Mumbai engineering and seaside skylines.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=19.0365,72.8172',
    ticketPrice: { amount: 85, currency: 'INR', pricingType: 'official', details: 'Official single vehicular toll ₹85; free viewing from Bandra Fort promenade' },
    openingHours: 'Open 24 hours (Bandra Fort promenade 06:00 - 19:30)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 45,
      walkingDistanceMeters: 400,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Sunset from Bandra Bandstand / Castella de Aguada',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-bwsl-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bandra_Worli_Sea_Link_Mumbai.jpg/1280px-Bandra_Worli_Sea_Link_Mumbai.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bandra_Worli_Sea_Link_Mumbai.jpg/400px-Bandra_Worli_Sea_Link_Mumbai.jpg',
        title: 'Bandra-Worli Sea Link cables spanning Mahim Bay',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'MSRDC',
      }
    ],
    source: 'Maharashtra State Road Development Corporation',
    lastUpdated: new Date().toISOString(),
  },

  // 57. DELHI - Rashtrapati Bhavan
  {
    id: 'attr-rashtrapati-bhavan',
    name: 'Rashtrapati Bhavan & Amrit Udyan',
    category: 'Official Presidential Residence & Classical Gardens',
    lat: 28.6143,
    lng: 77.1994,
    address: 'Raisina Hill, New Delhi, Delhi 110004',
    shortDescription: 'Colossal 340-room presidential mansion on Raisina Hill designed by Edwin Lutyens, featuring the iconic Central Dome and 15-acre Mughal-style Amrit Udyan gardens.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=28.6143,77.1994',
    ticketPrice: {
      amount: 50,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 50 per visitor (advance online booking on President of India portal); children below 8 free',
    },
    openingHours: '09:30 - 17:30 (Thursdays to Sundays by booking)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 1000,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning tour slot or February-March when Amrit Udyan roses bloom',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-rb-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Rashtrapati_Bhavan_New_Delhi.jpg/1280px-Rashtrapati_Bhavan_New_Delhi.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Rashtrapati_Bhavan_New_Delhi.jpg/400px-Rashtrapati_Bhavan_New_Delhi.jpg',
        title: 'Rashtrapati Bhavan dome on Raisina Hill',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'President of India Secretariat',
      }
    ],
    source: "President's Secretariat, Govt. of India",
    lastUpdated: new Date().toISOString(),
  },

  // 58. DELHI - Lotus Temple
  {
    id: 'attr-lotus-temple-delhi',
    name: 'Lotus Temple (Baháʼí House of Worship)',
    category: 'Expressionist Architectural Wonder & Meditation Sanctuary',
    lat: 28.5535,
    lng: 77.2588,
    address: 'Lotus Temple Road, Bahapur, Shambhu Dayal Bagh, Kalkaji, New Delhi 110019',
    shortDescription: 'World-famous lotus-shaped marble temple composed of 27 free-standing petals arranged in clusters of three to form nine doors opening onto a central hall.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=28.5535,77.2588',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free entry for people of all faiths and beliefs' },
    openingHours: '08:30 - 17:00 (Closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 75,
      walkingDistanceMeters: 600,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Late afternoon 16:00 (Peaceful meditation atmosphere)',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-lt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Lotus_Temple_in_New_Delhi_03-2016.jpg/1280px-Lotus_Temple_in_New_Delhi_03-2016.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Lotus_Temple_in_New_Delhi_03-2016.jpg/400px-Lotus_Temple_in_New_Delhi_03-2016.jpg',
        title: 'Pure white marble petals of Lotus Temple reflecting in ponds',
        author: 'A.Savin',
        license: 'FAL',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'National Spiritual Assembly of the Baháʼís of India',
    lastUpdated: new Date().toISOString(),
  },

  // 59. KANYAKUMARI - Vivekananda Rock Memorial
  {
    id: 'attr-vivekananda-rock-memorial',
    name: 'Vivekananda Rock Memorial & Thiruvalluvar Statue',
    category: 'Sacred Island Monument & Confluence of Three Oceans',
    lat: 8.0780,
    lng: 77.5552,
    address: 'Kanyakumari Offshore Rocks, Tamil Nadu 629702',
    shortDescription: 'Island rock memorial situated 500 meters offshore where Swami Vivekananda meditated in 1892 at the sacred confluence of the Arabian Sea, Bay of Bengal and Indian Ocean.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=8.0780,77.5552',
    ticketPrice: {
      amount: 20,
      currency: 'INR',
      pricingType: 'official',
      details: 'Memorial entry ₹20; Poompuhar Shipping ferry ticket ₹50 roundtrip',
    },
    openingHours: '08:00 - 16:00 Daily (Ferry operates weather permitting)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 500,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning ferry ride for calm seas and panoramic ocean views',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-vrm-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Vivekananda_Rock_Memorial%2C_Kanyakumari.jpg/1280px-Vivekananda_Rock_Memorial%2C_Kanyakumari.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Vivekananda_Rock_Memorial%2C_Kanyakumari.jpg/400px-Vivekananda_Rock_Memorial%2C_Kanyakumari.jpg',
        title: 'Vivekananda Rock Memorial surrounded by the Indian Ocean',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Vivekananda Kendra',
      }
    ],
    source: 'Vivekananda Kendra Kanyakumari',
    lastUpdated: new Date().toISOString(),
  },

  // 60. STATUE OF UNITY - Kevadia / Ekta Nagar
  {
    id: 'attr-statue-of-unity',
    name: 'Statue of Unity & Sardar Sarovar Dam',
    category: "World's Tallest Monument (182 meters)",
    lat: 21.8380,
    lng: 73.7191,
    address: 'Sardar Sarovar Dam, Ekta Nagar, Kevadia, Narmada District, Gujarat 393155',
    shortDescription: "Standing 182 meters (597 ft) tall facing the Narmada River, honoring Sardar Vallabhbhai Patel with high-speed viewing gallery elevators at 153 meters.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=21.8380,73.7191',
    ticketPrice: {
      amount: 150,
      currency: 'INR',
      pricingType: 'official',
      details: 'Basic entry ₹150 for adults (₹90 kids); Viewing Gallery ticket ₹380 (₹230 kids)',
    },
    openingHours: '08:00 - 18:00 (Light & Sound Laser Show at 19:15; Closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 180,
      walkingDistanceMeters: 1200,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'moderate',
      bestVisitingTime: 'Afternoon leading into evening 19:15 laser projection show',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-sou-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Statue_of_Unity.jpg/1280px-Statue_of_Unity.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Statue_of_Unity.jpg/400px-Statue_of_Unity.jpg',
        title: 'Statue of Unity 182-meter bronze colossus over Narmada River',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Sardar Vallabhbhai Patel Rashtriya Ekta Trust',
      }
    ],
    source: 'Statue of Unity Area Development and Tourism Governance Authority',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-valley-of-flowers-kevadia',
    name: 'Valley of Flowers & Cactus Garden, Ekta Nagar',
    category: 'Botanical Sanctuary & Nature Reserve',
    lat: 21.8320,
    lng: 73.7250,
    address: 'Ekta Nagar, Near Statue of Unity, Narmada, Gujarat 393155',
    shortDescription: '24-acre vibrant floral park blooming along the banks of the Narmada River, featuring ornamental flora, selfie points, and exotic desert succulents.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=21.8320,73.7250',
    ticketPrice: { amount: 60, currency: 'INR', pricingType: 'official', details: 'Included in composite circuit ticket or ₹60 individual' },
    openingHours: '08:00 - 18:00 (Closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 700,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'medium',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or late afternoon',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-vof-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Valley_of_Flowers_Statue_of_Unity.jpg/1280px-Valley_of_Flowers_Statue_of_Unity.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Valley_of_Flowers_Statue_of_Unity.jpg/400px-Valley_of_Flowers_Statue_of_Unity.jpg',
        title: 'Valley of Flowers garden bordering the Statue of Unity vista',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Gujarat Tourism',
      }
    ],
    source: 'Gujarat Tourism Development',
    lastUpdated: new Date().toISOString(),
  }
];
