import { AttractionItem } from '../../src/types.js';

export const CURATED_MONUMENTS: AttractionItem[] = [
  // 02. DELHI - Qutub Minar Complex
  {
    id: 'attr-qutub-minar',
    name: 'Qutub Minar Complex & Iron Pillar',
    category: 'UNESCO World Heritage Site & Indo-Islamic Architecture',
    lat: 28.5245,
    lng: 77.1855,
    address: 'Seth Sarai, Mehrauli, New Delhi, Delhi 110030',
    shortDescription: '72.5-meter red sandstone minaret begun by Qutb-ud-din Aibak in 1199, standing beside the rust-resistant 1,600-year-old Gupta Iron Pillar of Delhi and Alai Darwaza.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=28.5245,77.1855',
    ticketPrice: {
      amount: 40,
      currency: 'INR',
      pricingType: 'official',
      details: 'ASI ticket ₹40 for Indians, ₹600 for foreign tourists (Cashless ₹35)',
    },
    openingHours: '07:00 - 21:00 Daily (Illuminated in evenings)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 750,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or dusk for dramatic architectural shadows and floodlights',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-qm-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Qutub_Minar%2C_Delhi.jpg/1280px-Qutub_Minar%2C_Delhi.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Qutub_Minar%2C_Delhi.jpg/400px-Qutub_Minar%2C_Delhi.jpg',
        title: 'Qutub Minar soaring against clear skies in Mehrauli',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },

  // 03. DELHI - India Gate & Kartavya Path
  {
    id: 'attr-india-gate',
    name: 'India Gate & National War Memorial',
    category: 'National Memorial Arch & Ceremonial Boulevard',
    lat: 28.6129,
    lng: 77.2295,
    address: 'Kartavya Path, India Gate, New Delhi, Delhi 110001',
    shortDescription: '42-meter triumphal arch designed by Sir Edwin Lutyens honoring 84,000 soldiers, fronting the Amar Jawan Jyoti and newly inaugurated National War Memorial.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=28.6129,77.2295',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free open public monument' },
    openingHours: 'Open 24 hours (Kartavya Path lawns open day and night)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 800,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Evening 18:30 when the arch and fountains illuminate with tricolor lights',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-ig-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/India_Gate_in_New_Delhi_03-2016.jpg/1280px-India_Gate_in_New_Delhi_03-2016.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/India_Gate_in_New_Delhi_03-2016.jpg/400px-India_Gate_in_New_Delhi_03-2016.jpg',
        title: 'India Gate arch illuminated on Kartavya Path',
        author: 'A.Savin',
        license: 'FAL',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },

  // 04. MUMBAI - Gateway of India
  {
    id: 'attr-gateway-of-india',
    name: 'Gateway of India, Mumbai',
    category: 'Colonial Triumphal Arch & Harbor Waterfront',
    lat: 18.9220,
    lng: 72.8347,
    address: 'Apollo Bandar, Colaba, Mumbai, Maharashtra 400001',
    shortDescription: '26-meter yellow basalt archway built in 1924 overlooking the Arabian Sea, standing opposite the historic Taj Mahal Palace Hotel and harbor ferry terminal.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=18.9220,72.8347',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free public seaside promenade' },
    openingHours: 'Open 24 hours (Security access checkpoint at entrance)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 45,
      walkingDistanceMeters: 400,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Early sunrise breeze or sunset twilight',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-goi-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mumbai_03-2016_30_Gateway_of_India.jpg/1280px-Mumbai_03-2016_30_Gateway_of_India.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Mumbai_03-2016_30_Gateway_of_India.jpg/400px-Mumbai_03-2016_30_Gateway_of_India.jpg',
        title: 'Gateway of India framed against Mumbai Harbor',
        author: 'A.Savin',
        license: 'FAL',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },

  // 05. HYDERABAD - Charminar & Mecca Masjid
  {
    id: 'attr-charminar-hyderabad',
    name: 'Charminar & Mecca Masjid',
    category: 'Qutb Shahi Heritage Monument & Four Minarets',
    lat: 17.3616,
    lng: 78.4747,
    address: 'Charminar Road, Char Kaman, Ghansi Bazaar, Hyderabad, Telangana 500002',
    shortDescription: 'Iconic 1591 CE monument built by Muhammad Quli Qutb Shah to commemorate the end of plague, boasting four 48.7m stucco minarets and 45 prayer spaces.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=17.3616,78.4747',
    ticketPrice: {
      amount: 25,
      currency: 'INR',
      pricingType: 'official',
      details: 'ASI ticket ₹25 for Indians, ₹300 for foreign visitors',
    },
    openingHours: '09:00 - 17:30 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 450,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning before crowded bazaar or evening light illumination',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-cm-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Charminar_Hyderabad_1.jpg/1280px-Charminar_Hyderabad_1.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Charminar_Hyderabad_1.jpg/400px-Charminar_Hyderabad_1.jpg',
        title: 'Charminar minarets in Old Hyderabad',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },

  // 06. SANCHI - Great Stupa
  {
    id: 'attr-sanchi-stupa',
    name: 'Sanchi Stupa (Great Stupa 1 & Buddhist Complex)',
    category: 'UNESCO World Heritage Site & Mauryan Buddhist Art',
    lat: 23.4793,
    lng: 77.7397,
    address: 'Sanchi Hill, Raisen District, Madhya Pradesh 464661',
    shortDescription: 'One of the oldest stone structures in India commissioned by Emperor Ashoka in the 3rd century BCE, famed for four intricately carved ceremonial Torana gateways.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=23.4793,77.7397',
    ticketPrice: {
      amount: 40,
      currency: 'INR',
      pricingType: 'official',
      details: 'ASI ticket ₹40 for Indians, ₹600 for foreign visitors; children below 15 free',
    },
    openingHours: '06:30 - 18:30 Daily (Sunrise to Sunset)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 100,
      walkingDistanceMeters: 750,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Early morning sunrise on hill or winter afternoons',
      weatherSuitability: 'all_weather',
      crowdLevel: 'low',
    },
    photos: [
      {
        id: 'wm-ss-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Great_Stupa_at_Sanchi_Madhya_Pradesh.jpg/1280px-Great_Stupa_at_Sanchi_Madhya_Pradesh.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Great_Stupa_at_Sanchi_Madhya_Pradesh.jpg/400px-Great_Stupa_at_Sanchi_Madhya_Pradesh.jpg',
        title: 'The Great Stupa at Sanchi with carved southern gateway',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },

  // 08. AJANTA CAVES (Maharashtra)
  {
    id: 'attr-ajanta-caves',
    name: 'Ajanta Caves (Rock-cut Buddhist Monuments)',
    category: 'UNESCO World Heritage Site & Ancient Murals',
    lat: 20.5519,
    lng: 75.7033,
    address: 'Ajanta, Chhatrapati Sambhaji Nagar District, Maharashtra 431117',
    shortDescription: '30 rock-cut Buddhist cave monuments dating from the 2nd century BCE to about 480 CE, containing world-masterpiece tempera paintings depicting Jataka tales.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=20.5519,75.7033',
    ticketPrice: {
      amount: 40,
      currency: 'INR',
      pricingType: 'official',
      details: 'ASI ticket ₹40 for Indians, ₹600 for foreign visitors; shuttle bus fee ₹25-30',
    },
    openingHours: '09:00 - 17:00 (Closed Mondays)',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 180,
      walkingDistanceMeters: 1400,
      accessibility: 'partially_accessible',
      wheelchairSuitability: false,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning 09:30 when natural canyon light enters cave portals',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-ac-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ajanta_Caves_Panoramic_View.jpg/1280px-Ajanta_Caves_Panoramic_View.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Ajanta_Caves_Panoramic_View.jpg/400px-Ajanta_Caves_Panoramic_View.jpg',
        title: 'Horseshoe ravine cliff face of Ajanta Caves',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },

  // 09. ELLORA CAVES & KAILASH TEMPLE
  {
    id: 'attr-ellora-caves',
    name: 'Ellora Caves & Kailash Rock-Cut Temple (Cave 16)',
    category: 'UNESCO World Heritage Site & Monolithic Wonder',
    lat: 20.0268,
    lng: 75.1790,
    address: 'Ellora, Chhatrapati Sambhaji Nagar, Maharashtra 431102',
    shortDescription: 'World’s largest monolithic rock excavation carved out of a single basalt cliff (Kailash Temple, Cave 16) alongside 34 Buddhist, Hindu, and Jain rock sanctuaries.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=20.0268,75.1790',
    ticketPrice: {
      amount: 40,
      currency: 'INR',
      pricingType: 'official',
      details: 'ASI ticket ₹40 for Indians, ₹600 for foreign visitors',
    },
    openingHours: '06:00 - 18:00 (Closed Tuesdays)',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 180,
      walkingDistanceMeters: 1600,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning hours for Cave 16 Kailash Temple front view',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-ec-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Kailash_temple%2C_cave_16_at_Ellora.jpg/1280px-Kailash_temple%2C_cave_16_at_Ellora.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Kailash_temple%2C_cave_16_at_Ellora.jpg/400px-Kailash_temple%2C_cave_16_at_Ellora.jpg',
        title: 'Monolithic Kailash Temple excavated from top to bottom at Ellora',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  }
];
