import { AttractionItem } from '../../src/types.js';

export const CURATED_MUSEUMS: AttractionItem[] = [
  // 1. KOLKATA - Indian Museum & Victoria Memorial
  {
    id: 'attr-indian-museum-kolkata',
    name: 'Indian Museum, Kolkata (Jadu Ghar)',
    category: 'National Heritage & Antiquities Museum',
    lat: 22.5579,
    lng: 88.3511,
    address: '27 Jawaharlal Nehru Road, Park Street area, Kolkata, West Bengal 700016',
    shortDescription: 'The ninth oldest museum in the world and largest in India, established in 1814, featuring rare collections of Indian art, fossils, meteorites, and an Egyptian mummy.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=22.5579,88.3511',
    ticketPrice: {
      amount: 50,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 50 for Indians, INR 500 for foreign visitors; children under 5 free',
    },
    openingHours: '10:00 - 18:00 (Closed Mondays & National Holidays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 900,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning 10:30 (Quiet gallery hours)',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-imk-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Indian_Museum%2C_Kolkata.jpg/1280px-Indian_Museum%2C_Kolkata.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Indian_Museum%2C_Kolkata.jpg/400px-Indian_Museum%2C_Kolkata.jpg',
        title: 'Grand neoclassical facade of Indian Museum Kolkata',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Indian Museum Kolkata',
      }
    ],
    source: 'Ministry of Culture, Govt. of India',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-victoria-memorial-kolkata',
    name: 'Victoria Memorial Hall & Gardens',
    category: 'Monumental Marble Museum & Royal Gardens',
    lat: 22.5448,
    lng: 88.3426,
    address: '1 Queen’s Way, Maidan, Kolkata, West Bengal 700071',
    shortDescription: 'Colossal white Makrana marble palace built between 1906 and 1921, set in 64 acres of landscaped gardens with Royal Gallery paintings and royal memorabilia.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=22.5448,88.3426',
    ticketPrice: {
      amount: 50,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 50 for museum & gardens (INR 20 gardens only), INR 500 foreign nationals',
    },
    openingHours: '10:00 - 18:00 (Gardens 05:30 - 18:15 daily, Gallery closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 110,
      walkingDistanceMeters: 1000,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Late afternoon 15:30 with sunset across reflecting lakes',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-vmk-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Victoria_Memorial_situated_in_Kolkata.jpg/1280px-Victoria_Memorial_situated_in_Kolkata.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Victoria_Memorial_situated_in_Kolkata.jpg/400px-Victoria_Memorial_situated_in_Kolkata.jpg',
        title: 'Victoria Memorial reflection in Maidan water gardens',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Victoria Memorial Hall Trust',
      }
    ],
    source: 'Ministry of Culture, Govt. of India',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-howrah-bridge-kolkata',
    name: 'Howrah Bridge (Rabindra Setu)',
    category: 'Iconic Balanced Cantilever Bridge',
    lat: 22.5851,
    lng: 88.3468,
    address: 'Howrah, Kolkata, West Bengal 700001',
    shortDescription: 'World-famous balanced cantilever steel suspension bridge over the Hooghly River, constructed without nuts and bolts, carrying over 100,000 vehicles daily.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=22.5851,88.3468',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free public engineering marvel' },
    openingHours: 'Open 24 hours (Best viewed from ferry or Millenium Park promenade)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 40,
      walkingDistanceMeters: 700,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Dawn mist or night illumination from ferry',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-hb-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Howrah_bridge_at_night.jpg/1280px-Howrah_bridge_at_night.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Howrah_bridge_at_night.jpg/400px-Howrah_bridge_at_night.jpg',
        title: 'Howrah Bridge illuminated over the Hooghly River',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Kolkata Port Trust',
      }
    ],
    source: 'Syama Prasad Mookerjee Port Kolkata',
    lastUpdated: new Date().toISOString(),
  },

  // 2. DELHI - National Museum & Kartavya Path
  {
    id: 'attr-national-museum-delhi',
    name: 'National Museum, New Delhi',
    category: 'National Apex Cultural & Archaeological Museum',
    lat: 28.6118,
    lng: 77.2193,
    address: 'Janpath, Rajpath Area, Central Secretariat, New Delhi, Delhi 110011',
    shortDescription: 'Premier national museum holding over 200,000 works spanning 5,000 years, including the Dancing Girl of Mohenjo-daro, Buddhist relics, and Tanjore paintings.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=28.6118,77.2193',
    ticketPrice: {
      amount: 20,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 20 for Indian citizens, INR 650 for foreign tourists with free audio guide',
    },
    openingHours: '10:00 - 18:00 (Closed Mondays & Gazetted Holidays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 800,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning 10:30',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'low',
    },
    photos: [
      {
        id: 'wm-nmd-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/National_Museum_New_Delhi.jpg/1280px-National_Museum_New_Delhi.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/National_Museum_New_Delhi.jpg/400px-National_Museum_New_Delhi.jpg',
        title: 'National Museum rotunda entrance, Janpath, New Delhi',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'National Museum New Delhi',
      }
    ],
    source: 'Ministry of Culture, Govt. of India',
    lastUpdated: new Date().toISOString(),
  },

  // 3. MUMBAI - CSMVS & Dr. Bhau Daji Lad Museum
  {
    id: 'attr-csmvs-mumbai',
    name: 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (CSMVS)',
    category: 'Indo-Saracenic Art & History Museum & UNESCO Heritage Award',
    lat: 18.9269,
    lng: 72.8327,
    address: '159-161 Mahatma Gandhi Road, Fort, Mumbai, Maharashtra 400023',
    shortDescription: 'Grade I heritage monument built in British-Raj era with grand dome inspired by Gol Gumbaz, housing 70,000 historic antiquities, miniature paintings and Japanese art.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=18.9269,72.8327',
    ticketPrice: {
      amount: 150,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 150 for adults, INR 50 for children/students, INR 700 for foreign visitors',
    },
    openingHours: '10:15 - 18:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 800,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'moderate',
      bestVisitingTime: 'Morning 11:00 or early afternoon',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-csmvs-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Prince_of_Wales_Museum_Mumbai_2011.jpg/1280px-Prince_of_Wales_Museum_Mumbai_2011.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Prince_of_Wales_Museum_Mumbai_2011.jpg/400px-Prince_of_Wales_Museum_Mumbai_2011.jpg',
        title: 'The magnificent Indo-Saracenic dome and gardens of CSMVS Mumbai',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 3.0',
        source: 'CSMVS Museum Board',
      }
    ],
    source: 'CSMVS Trust Board',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-dr-bhau-daji-lad-museum',
    name: 'Dr. Bhau Daji Lad Museum (Oldest Museum in Mumbai)',
    category: 'Victorian Decorative Arts & City History Museum',
    lat: 18.9789,
    lng: 72.8354,
    address: '91 A, Rani Baug, Veer Mata Jijabai Bhonsle Udyan, Byculla East, Mumbai, Maharashtra 400027',
    shortDescription: "Mumbai's oldest museum established in 1855, awarded UNESCO Asia-Pacific Heritage Award for its High Victorian Palladian gilded columns and Minton tile floors.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=18.9789,72.8354',
    ticketPrice: {
      amount: 20,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 20 for Indians, INR 10 for students, INR 300 for foreign visitors',
    },
    openingHours: '10:00 - 18:00 (Closed Wednesdays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 75,
      walkingDistanceMeters: 450,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or early afternoon',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'low',
    },
    photos: [
      {
        id: 'wm-bdl-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dr_Bhau_Daji_Lad_Museum_Mumbai.jpg/1280px-Dr_Bhau_Daji_Lad_Museum_Mumbai.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dr_Bhau_Daji_Lad_Museum_Mumbai.jpg/400px-Dr_Bhau_Daji_Lad_Museum_Mumbai.jpg',
        title: 'Victorian ornate interior of Dr. Bhau Daji Lad Museum',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Municipal Corporation of Greater Mumbai',
      }
    ],
    source: 'Municipal Corporation of Greater Mumbai & Jamnalal Bajaj Trust',
    lastUpdated: new Date().toISOString(),
  },

  // 4. HYDERABAD - Salar Jung Museum
  {
    id: 'attr-salar-jung-museum',
    name: 'Salar Jung Museum',
    category: 'National Art Museum & One-Man Collector Legacy',
    lat: 17.3713,
    lng: 78.4804,
    address: 'Salar Jung Marg, Darulshifa, Hyderabad, Telangana 500002',
    shortDescription: "One of the three National Museums of India housing the legendary single-family collection of Salar Jung III, including the Veiled Rebecca and 19th-century musical clock.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=17.3713,78.4804',
    ticketPrice: {
      amount: 50,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 50 for Indians, INR 20 for students, INR 500 for foreign visitors',
    },
    openingHours: '10:00 - 17:00 (Closed Fridays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 150,
      walkingDistanceMeters: 1000,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning 10:30 before the 12:00 clock chime show',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-sjm-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Salar_Jung_Museum%2C_Hyderabad.jpg/1280px-Salar_Jung_Museum%2C_Hyderabad.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Salar_Jung_Museum%2C_Hyderabad.jpg/400px-Salar_Jung_Museum%2C_Hyderabad.jpg',
        title: 'Musi riverfront building of Salar Jung Museum Hyderabad',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Salar Jung Museum Board',
      }
    ],
    source: 'Ministry of Culture, Govt. of India',
    lastUpdated: new Date().toISOString(),
  },

  // 5. JAIPUR - Albert Hall Museum
  {
    id: 'attr-albert-hall-museum',
    name: 'Albert Hall Museum (Central Museum Jaipur)',
    category: 'Indo-Saracenic Royal Museum',
    lat: 26.9116,
    lng: 75.8195,
    address: 'Ram Niwas Garden, Kailash Puri, Adarsh Nagar, Jaipur, Rajasthan 302004',
    shortDescription: 'Oldest museum of Rajasthan founded in 1876, famed for Indo-Saracenic archways, Persian carpets, ivory carvings, metal ware, and an authentic Egyptian mummy.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=26.9116,75.8195',
    ticketPrice: {
      amount: 40,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 40 for Indians, INR 300 for foreign visitors; Night viewing INR 100',
    },
    openingHours: '09:00 - 17:00, 19:00 - 22:00 (Night viewing)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 80,
      walkingDistanceMeters: 600,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Evening 19:00 for breathtaking color-changing illumination',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-ahm-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Albert_Hall_Museum%2C_Jaipur.jpg/1280px-Albert_Hall_Museum%2C_Jaipur.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Albert_Hall_Museum%2C_Jaipur.jpg/400px-Albert_Hall_Museum%2C_Jaipur.jpg',
        title: 'Albert Hall Museum framed against Ram Niwas Garden pigeons',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Department of Archaeology, Rajasthan',
      }
    ],
    source: 'Department of Archaeology and Museums, Rajasthan',
    lastUpdated: new Date().toISOString(),
  },

  // 6. CHENNAI - Government Museum (Egmore)
  {
    id: 'attr-government-museum-chennai',
    name: 'Government Museum, Chennai (Egmore Museum)',
    category: 'Apex State Antiquities & Chola Bronzes Museum',
    lat: 13.0732,
    lng: 80.2570,
    address: 'Pantheon Road, Egmore, Chennai, Tamil Nadu 600008',
    shortDescription: 'Established in 1851, the second oldest museum in India, globally celebrated for the world’s finest gallery of Chola Bronze sculptures including Nataraja.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=13.0732,80.2570',
    ticketPrice: {
      amount: 15,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 15 for adults, INR 10 for students, INR 250 for foreign tourists',
    },
    openingHours: '09:30 - 17:00 (Closed Fridays & National Holidays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 100,
      walkingDistanceMeters: 750,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning 10:00 for the Chola Bronze gallery',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-gmc-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Government_Museum_Chennai.jpg/1280px-Government_Museum_Chennai.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Government_Museum_Chennai.jpg/400px-Government_Museum_Chennai.jpg',
        title: 'Red sandstone British-colonial facade of Egmore Museum Chennai',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Tamil Nadu Museums Department',
      }
    ],
    source: 'Department of Museums, Govt. of Tamil Nadu',
    lastUpdated: new Date().toISOString(),
  },

  // 7. PATNA - Bihar Museum
  {
    id: 'attr-bihar-museum-patna',
    name: 'Bihar Museum, Patna',
    category: 'State-of-the-Art Heritage & History Museum',
    lat: 25.6093,
    lng: 85.1235,
    address: 'Bailey Road, Jawaharlal Nehru Marg, Patna, Bihar 800001',
    shortDescription: 'World-class modern museum designed by Maki & Associates, spanning 13 acres with the historic Didarganj Yakshi, Mauryan dynasty art, and regional folklore.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=25.6093,85.1235',
    ticketPrice: {
      amount: 100,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 100 for adults, INR 50 for children/students, INR 500 for foreign visitors',
    },
    openingHours: '10:00 - 17:00 (Closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 850,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'moderate',
      bestVisitingTime: 'Morning or early afternoon',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-bmp-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Bihar_Museum_Patna.jpg/1280px-Bihar_Museum_Patna.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Bihar_Museum_Patna.jpg/400px-Bihar_Museum_Patna.jpg',
        title: 'Corten steel architecture and courtyards of Bihar Museum Patna',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Bihar Museum Society',
      }
    ],
    source: 'Government of Bihar',
    lastUpdated: new Date().toISOString(),
  },

  // 10. AHMEDABAD - Calico Museum of Textiles
  {
    id: 'attr-calico-museum-textiles',
    name: 'Calico Museum of Textiles, Ahmedabad',
    category: 'Premier Indian Textile Heritage Museum',
    lat: 23.0573,
    lng: 72.5936,
    address: 'The Retreat, Opposite Underbridge, Shahibaug, Ahmedabad, Gujarat 380004',
    shortDescription: "Premier textile museum of India holding five centuries of Indian textiles, courtly fabrics, Pichhwais, Kashmiri shawls, and tie-dye patola silks in a historic haveli.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=23.0573,72.5936',
    ticketPrice: {
      amount: 0,
      currency: 'INR',
      pricingType: 'official',
      details: 'Free admission via mandatory online reservation on Sarabhai Foundation portal',
    },
    openingHours: '10:30 - 13:00 (Guided tours by pre-booking; closed Wednesdays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 500,
      accessibility: 'partially_accessible',
      wheelchairSuitability: false,
      indoorOutdoor: 'indoor',
      childSuitability: false,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning 10:15 appointment slot',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'low',
    },
    photos: [
      {
        id: 'wm-cmt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Calico_Museum_of_Textiles_Ahmedabad.jpg/1280px-Calico_Museum_of_Textiles_Ahmedabad.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Calico_Museum_of_Textiles_Ahmedabad.jpg/400px-Calico_Museum_of_Textiles_Ahmedabad.jpg',
        title: 'Intricate wooden carved haveli courtyard at Calico Museum',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Sarabhai Foundation',
      }
    ],
    source: 'Sarabhai Foundation',
    lastUpdated: new Date().toISOString(),
  }
];
