import { AttractionItem } from '../../src/types.js';

export const CURATED_TEMPLES: AttractionItem[] = [
  // 1. AMRITSAR - Golden Temple & Surrounds
  {
    id: 'attr-golden-temple',
    name: 'Sri Harmandir Sahib (Golden Temple)',
    category: 'Sacred Gurdwara & Spiritual Heritage',
    lat: 31.6200,
    lng: 74.8765,
    address: 'Golden Temple Road, Atta Mandi, Amritsar, Punjab 143006',
    shortDescription: 'The holiest gurdwara of Sikhism, adorned with gold leaf foil, centered in the holy Amrit Sarovar tank with 24/7 community langar.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=31.6200,74.8765',
    ticketPrice: {
      amount: 0,
      currency: 'INR',
      pricingType: 'official',
      details: 'Free entry for all pilgrims and visitors; Langar free for everyone',
    },
    openingHours: 'Open 24 hours daily (Palki Sahib early morning and night)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 800,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Early morning sunrise or night illuminated',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-gt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/The_Golden_Temple_of_Amritsar_Punjab_India.jpg/1280px-The_Golden_Temple_of_Amritsar_Punjab_India.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/The_Golden_Temple_of_Amritsar_Punjab_India.jpg/400px-The_Golden_Temple_of_Amritsar_Punjab_India.jpg',
        title: 'Golden Temple illuminating over Amrit Sarovar',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Shiromani Gurdwara Parbandhak Committee',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-jallianwala-bagh',
    name: 'Jallianwala Bagh Memorial',
    category: 'National Historical Memorial',
    lat: 31.6206,
    lng: 74.8801,
    address: 'Golden Temple Road, Amritsar, Punjab 143006',
    shortDescription: 'Historic public garden and national memorial commemorating the 1919 massacre victims, with preserved bullet marks and Martyrs Well.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=31.6206,74.8801',
    ticketPrice: {
      amount: 0,
      currency: 'INR',
      pricingType: 'official',
      details: 'Free national memorial',
    },
    openingHours: '06:30 - 19:30 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 45,
      walkingDistanceMeters: 500,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'medium',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or late afternoon',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-jb-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Jallianwala_Bagh_Memorial%2C_Amritsar.jpg/1280px-Jallianwala_Bagh_Memorial%2C_Amritsar.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Jallianwala_Bagh_Memorial%2C_Amritsar.jpg/400px-Jallianwala_Bagh_Memorial%2C_Amritsar.jpg',
        title: 'Flame of Liberty memorial at Jallianwala Bagh',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-partition-museum-amritsar',
    name: 'Partition Museum',
    category: 'History & People Museum',
    lat: 31.6253,
    lng: 74.8778,
    address: 'Town Hall, Heritage Street, Amritsar, Punjab 143006',
    shortDescription: "The world's first museum dedicated to the memory of the 1947 Partition of British India, housing oral histories and archival artifacts.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=31.6253,74.8778',
    ticketPrice: {
      amount: 10,
      currency: 'INR',
      pricingType: 'official',
      details: 'INR 10 for Indians, INR 250 for foreign tourists',
    },
    openingHours: '10:00 - 18:00 (Closed Mondays)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 75,
      walkingDistanceMeters: 400,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'medium',
      budgetCategory: 'budget',
      bestVisitingTime: 'Afternoon (Air-conditioned)',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-pm-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Town_Hall_Amritsar.jpg/1280px-Town_Hall_Amritsar.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Town_Hall_Amritsar.jpg/400px-Town_Hall_Amritsar.jpg',
        title: 'Town Hall building housing the Partition Museum',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Arts and Cultural Heritage Trust',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-gobindgarh-fort',
    name: 'Gobindgarh Fort',
    category: 'Historic Military Citadel',
    lat: 31.6275,
    lng: 74.8569,
    address: 'Old Cantt Road, Vijay Chowk, Amritsar, Punjab 143001',
    shortDescription: '18th-century royal military bastion built by Maharaja Ranjit Singh, featuring the Toshakhana treasury and Sikh warfare galleries.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=31.6275,74.8569',
    ticketPrice: {
      amount: 50,
      currency: 'INR',
      pricingType: 'official',
      details: 'General entry tariff with access to courtyards & exhibits',
    },
    openingHours: '10:00 - 22:00 Daily',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 1000,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Late afternoon through evening light show',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-gf-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Fort_Gobindgarh_Amritsar.jpg/1280px-Fort_Gobindgarh_Amritsar.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Fort_Gobindgarh_Amritsar.jpg/400px-Fort_Gobindgarh_Amritsar.jpg',
        title: 'Grand entrance gate of Gobindgarh Fort',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Punjab Tourism Development',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-durgiana-temple',
    name: 'Durgiana Temple (Lakshmi Narayan Mandir)',
    category: 'Sacred Temple & Lake',
    lat: 31.6322,
    lng: 74.8682,
    address: 'Near Hathi Gate, Goal Bagh, Amritsar, Punjab 143001',
    shortDescription: 'Historic Hindu shrine architecturally inspired by the Golden Temple, set in the middle of a holy water tank dedicated to Goddess Durga.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=31.6322,74.8682',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free public entry' },
    openingHours: '06:00 - 22:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 50,
      walkingDistanceMeters: 500,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning prayers or dusk illumination',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-dt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Durgiana_Temple_Amritsar_India.jpg/1280px-Durgiana_Temple_Amritsar_India.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Durgiana_Temple_Amritsar_India.jpg/400px-Durgiana_Temple_Amritsar_India.jpg',
        title: 'Durgiana Mandir amidst temple lake waters',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Durgiana Temple Committee',
    lastUpdated: new Date().toISOString(),
  },

  // 2. VARANASI - Kashi Vishwanath & Ghats
  {
    id: 'attr-kashi-vishwanath',
    name: 'Shri Kashi Vishwanath Temple',
    category: 'Sacred Jyotirlinga & Temple Corridor',
    lat: 25.3109,
    lng: 83.0107,
    address: 'Vishwanath Gali, Lahori Tola, Varanasi, Uttar Pradesh 221001',
    shortDescription: 'One of the twelve sacred Jyotirlingas of Lord Shiva with a golden dome donated by Maharaja Ranjit Singh and modern Ganga corridor.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=25.3109,83.0107',
    ticketPrice: {
      amount: 0,
      currency: 'INR',
      pricingType: 'official',
      details: 'General darshan is free; special Sugam Darshan passes available via official shrine portal',
    },
    openingHours: '03:00 - 23:00 Daily (Mangala Aarti at 03:00)',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 600,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Early morning or after dusk Ganga Aarti',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-kv-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Ahilya_Ghat_by_the_Ganges%2C_Varanasi.jpg/1280px-Ahilya_Ghat_by_the_Ganges%2C_Varanasi.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Ahilya_Ghat_by_the_Ganges%2C_Varanasi.jpg/400px-Ahilya_Ghat_by_the_Ganges%2C_Varanasi.jpg',
        title: 'Ganga ghat approach to Kashi Vishwanath Dham',
        author: 'Marcell Sgier',
        license: 'CC BY-SA 4.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Kashi Vishwanath Temple Trust',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-dashashwamedh-ghat',
    name: 'Dashashwamedh Ghat & Evening Ganga Aarti',
    category: 'Sacred Riverfront & Living Cultural Heritage',
    lat: 25.3060,
    lng: 83.0105,
    address: 'Dashashwamedh Ghat Road, Varanasi, Uttar Pradesh 221001',
    shortDescription: 'The most spectacular riverfront ghat of Varanasi where the world-renowned synchronized evening Maha Ganga Aarti takes place with brass lamps.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=25.3060,83.0105',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free public viewing from ghat steps' },
    openingHours: 'Open 24 hours (Evening Aarti starts ~18:45)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 75,
      walkingDistanceMeters: 400,
      accessibility: 'partially_accessible',
      wheelchairSuitability: false,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: '18:00 to 19:45 for sunset and Aarti',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-dg-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Dashashwamedh_Ghat_Varanasi.jpg/1280px-Dashashwamedh_Ghat_Varanasi.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Dashashwamedh_Ghat_Varanasi.jpg/400px-Dashashwamedh_Ghat_Varanasi.jpg',
        title: 'Maha Ganga Aarti at Dashashwamedh Ghat',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Varanasi Smart City Development',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-sarnath-dhamek-stupa',
    name: 'Sarnath & Dhamek Stupa',
    category: 'Buddhist Sacred Monument & UNESCO Tentative',
    lat: 25.3811,
    lng: 83.0227,
    address: 'Sarnath, Varanasi District, Uttar Pradesh 221007',
    shortDescription: 'The sacred deer park where Gautama Buddha delivered his first sermon (Dhammacakkappavattana Sutta) and established the Sangha in 528 BCE.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=25.3811,83.0227',
    ticketPrice: { amount: 25, currency: 'INR', pricingType: 'official', details: 'Official ASI ticket; free for children under 15' },
    openingHours: 'Sunrise to Sunset (06:00 - 18:00)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 700,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning peaceful contemplation',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-sn-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Dhamekh_Stupa_Sarnath.jpg/1280px-Dhamekh_Stupa_Sarnath.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Dhamekh_Stupa_Sarnath.jpg/400px-Dhamekh_Stupa_Sarnath.jpg',
        title: 'Ancient Dhamek Stupa surrounded by Mauryan monastery ruins',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },

  // 3. MADURAI - Meenakshi Amman Temple
  {
    id: 'attr-meenakshi-temple',
    name: 'Meenakshi Amman Temple',
    category: 'Dravidian Architectural Wonder & Temple Complex',
    lat: 9.9195,
    lng: 78.1193,
    address: 'Madurai Main, Madurai, Tamil Nadu 625001',
    shortDescription: 'Centuries-old historic Hindu temple on the Vaigai River with 14 towering gopurams encrusted with thousands of colorful mythological stucco figures.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=9.9195,78.1193',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'General darshan free; Hall of 1000 Pillars ticket ₹50' },
    openingHours: '05:00 - 12:30, 16:00 - 22:00 Daily',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 900,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Early morning or late afternoon',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-mat-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Madurai_Meenakshi_Amman_Temple_South_Gopuram.jpg/1280px-Madurai_Meenakshi_Amman_Temple_South_Gopuram.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Madurai_Meenakshi_Amman_Temple_South_Gopuram.jpg/400px-Madurai_Meenakshi_Amman_Temple_South_Gopuram.jpg',
        title: 'Towering South Gopuram of Meenakshi Amman Temple',
        author: 'Bernard Gagnon',
        license: 'CC BY-SA 3.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Tamil Nadu HR&CE Department',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-thirumalai-nayakkar-mahal',
    name: 'Thirumalai Nayakkar Mahal',
    category: 'Indo-Saracenic Royal Palace',
    lat: 9.9152,
    lng: 78.1238,
    address: 'Panthadi 1st Street, Near Meenakshi Temple, Madurai, Tamil Nadu 625001',
    shortDescription: '17th-century palace built by King Thirumalai Nayak, celebrated for massive white stone pillars, domed durbar hall and evening sound and light shows.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=9.9152,78.1238',
    ticketPrice: { amount: 10, currency: 'INR', pricingType: 'official', details: 'INR 10 for Indians, INR 50 for foreign nationals' },
    openingHours: '09:00 - 17:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 500,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or 18:45 for Light & Sound Show',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-tnm-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Thirumalai_Nayakkar_Mahal%2C_Madurai.jpg/1280px-Thirumalai_Nayakkar_Mahal%2C_Madurai.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Thirumalai_Nayakkar_Mahal%2C_Madurai.jpg/400px-Thirumalai_Nayakkar_Mahal%2C_Madurai.jpg',
        title: 'Monumental pillared courtyard of Thirumalai Nayakkar Mahal',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Tamil Nadu Archaeology',
      }
    ],
    source: 'Tamil Nadu Archaeological Department',
    lastUpdated: new Date().toISOString(),
  },

  // 4. THANJAVUR - Brihadeeswarar Temple
  {
    id: 'attr-brihadeeswarar-temple',
    name: 'Brihadeeswarar Temple (Great Living Chola Temple)',
    category: 'UNESCO World Heritage Site & Chola Architecture',
    lat: 10.7828,
    lng: 79.1318,
    address: 'Membalam Road, Balaganapathy Nagar, Thanjavur, Tamil Nadu 613007',
    shortDescription: '1010 CE architectural triumph commissioned by Raja Raja Chola I with an 80-tonne monolithic granite kumbam atop a 216-ft Vimana tower.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=10.7828,79.1318',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free UNESCO monument entry managed by ASI' },
    openingHours: '06:00 - 12:30, 16:00 - 20:30 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 100,
      walkingDistanceMeters: 800,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Late afternoon when granite glows golden in sunset',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-bt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Brihadisvara_Temple_Thanjavur.jpg/1280px-Brihadisvara_Temple_Thanjavur.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Brihadisvara_Temple_Thanjavur.jpg/400px-Brihadisvara_Temple_Thanjavur.jpg',
        title: 'Granite Vimana of Brihadeeswarar Temple at sunset',
        author: 'Jean-Pierre Dalbéra',
        license: 'CC BY 2.0',
        source: 'Wikimedia Commons',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-thanjavur-palace',
    name: 'Thanjavur Maratha Palace & Saraswathi Mahal',
    category: 'Royal Palace & Ancient Manuscript Archive',
    lat: 10.7932,
    lng: 79.1362,
    address: 'East Main Street, Thanjavur, Tamil Nadu 613001',
    shortDescription: 'Official residence of the Nayak and Bhonsle Maratha rulers housing the legendary Saraswathi Mahal Library with medieval palm-leaf manuscripts.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=10.7932,79.1362',
    ticketPrice: { amount: 30, currency: 'INR', pricingType: 'official', details: 'INR 30 combined palace and art museum entry' },
    openingHours: '10:00 - 13:00, 14:00 - 17:30 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 75,
      walkingDistanceMeters: 600,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Mid-morning',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'low',
    },
    photos: [
      {
        id: 'wm-tmp-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Thanjavur_Palace.jpg/1280px-Thanjavur_Palace.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Thanjavur_Palace.jpg/400px-Thanjavur_Palace.jpg',
        title: 'Bell tower and durbar courtyard of Thanjavur Maratha Palace',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Tamil Nadu Tourism',
      }
    ],
    source: 'Tamil Nadu Tourism Development',
    lastUpdated: new Date().toISOString(),
  },

  // 5 & 6. KONARK & PURI (ODISHA)
  {
    id: 'attr-konark-sun-temple',
    name: 'Konark Sun Temple (Black Pagoda)',
    category: 'UNESCO World Heritage Site & Kalinga Architecture',
    lat: 19.8876,
    lng: 86.0945,
    address: 'Konark, Puri District, Odisha 752111',
    shortDescription: '13th-century CE colossal stone temple conceived as a gigantic cosmic chariot for the Sun God Surya, pulled by seven horses on 24 carved wheels.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=19.8876,86.0945',
    ticketPrice: { amount: 40, currency: 'INR', pricingType: 'official', details: 'Official ASI ticket; free for children below 15' },
    openingHours: '06:00 - 20:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 100,
      walkingDistanceMeters: 750,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Sunrise or late afternoon',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-kst-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Konark_Sun_Temple%2C_Odisha.jpg/1280px-Konark_Sun_Temple%2C_Odisha.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Konark_Sun_Temple%2C_Odisha.jpg/400px-Konark_Sun_Temple%2C_Odisha.jpg',
        title: 'The Great Chariot Jagamohana of Konark Sun Temple',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Archaeological Survey of India',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-chandrabhaga-beach',
    name: 'Chandrabhaga Beach (Blue Flag Certified)',
    category: 'Clean Coastal Reserve & Pilgrimage Shore',
    lat: 19.8655,
    lng: 86.1118,
    address: 'Marine Drive Road, Konark, Odisha 752111',
    shortDescription: 'Pristine coastal shoreline honored with the international eco-friendly Blue Flag certification, famed for sunrise panoramas.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=19.8655,86.1118',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free public beach' },
    openingHours: 'Open 24 hours (Lifeguards present sunrise to sunset)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 500,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'medium',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: '05:30 - 08:00 for sunrise over the Bay of Bengal',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-cb-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Chandrabhaga_Beach_Konark_Odisha.jpg/1280px-Chandrabhaga_Beach_Konark_Odisha.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Chandrabhaga_Beach_Konark_Odisha.jpg/400px-Chandrabhaga_Beach_Konark_Odisha.jpg',
        title: 'Morning tides on Chandrabhaga Blue Flag Beach',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Odisha Tourism',
      }
    ],
    source: 'Odisha Tourism Development',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-jagannath-temple-puri',
    name: 'Shree Jagannath Temple, Puri',
    category: 'Char Dham Sacred Shrine & Heritage Landmark',
    lat: 19.8049,
    lng: 85.8179,
    address: 'Grand Road, Puri, Odisha 752001',
    shortDescription: 'One of the four sacred Char Dham Hindu pilgrimage centers, celebrated for the annual Ratha Yatra and the world’s largest traditional temple kitchen (Mahaprasad).',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=19.8049,85.8179',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free temple entry; traditional offering counters official' },
    openingHours: '05:00 - 23:00 Daily',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 900,
      accessibility: 'partially_accessible',
      wheelchairSuitability: false,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning 06:00 - 09:00 or evening 18:00',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-jp-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Jagannath_Temple%2C_Puri%2C_Odisha.jpg/1280px-Jagannath_Temple%2C_Puri%2C_Odisha.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Jagannath_Temple%2C_Puri%2C_Odisha.jpg/400px-Jagannath_Temple%2C_Puri%2C_Odisha.jpg',
        title: 'Grand Vimana and Lion Gate of Shree Jagannath Temple, Puri',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Shree Jagannath Temple Administration',
      }
    ],
    source: 'Shree Jagannath Temple Administration',
    lastUpdated: new Date().toISOString(),
  },

  // 7. BADRINATH - Himalayan Char Dham
  {
    id: 'attr-badrinath-temple',
    name: 'Badrinath Temple (Badri Vishal)',
    category: 'Char Dham Himalayan Sacred Shrine',
    lat: 30.7433,
    lng: 79.4938,
    address: 'Badrinath, Chamoli District, Uttarakhand 246422',
    shortDescription: 'Dedicated to Lord Vishnu, situated along the banks of the Alaknanda River at an altitude of 3,133 meters between Nar and Narayana mountain ranges.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.7433,79.4938',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free darshan for all pilgrims; seasonal pilgrimage' },
    openingHours: '04:30 - 13:00, 16:00 - 21:00 (Open May to November annually)',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 600,
      accessibility: 'partially_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning after bathing in sacred Tapt Kund',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-bn-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Badrinath_Temple_front_view.jpg/1280px-Badrinath_Temple_front_view.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Badrinath_Temple_front_view.jpg/400px-Badrinath_Temple_front_view.jpg',
        title: 'Colorful facade of Badrinath Temple against alpine peaks',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Uttarakhand Tourism',
      }
    ],
    source: 'Shri Badrinath-Kedarnath Temple Committee',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-mana-village',
    name: 'Mana Village & Bheem Pul (First Village of India)',
    category: 'Himalayan Border Heritage Village',
    lat: 30.7686,
    lng: 79.4965,
    address: 'Mana, Near Badrinath, Chamoli District, Uttarakhand 246422',
    shortDescription: "Designated as India's 'First Village', featuring the natural stone bridge Bheem Pul over foaming Saraswati River and mythical Vyas Gufa.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=30.7686,79.4965',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free village walking tour' },
    openingHours: 'Daylight hours (07:00 - 18:00)',
    taxonomy: {
      difficultyLevel: 'moderate',
      estimatedDurationMinutes: 80,
      walkingDistanceMeters: 900,
      accessibility: 'partially_accessible',
      wheelchairSuitability: false,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Clear sunny mornings',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-mv-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Mana_Village_Badrinath.jpg/1280px-Mana_Village_Badrinath.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Mana_Village_Badrinath.jpg/400px-Mana_Village_Badrinath.jpg',
        title: 'Bheem Pul natural rock bridge in Mana Village',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Uttarakhand Tourism',
      }
    ],
    source: 'Uttarakhand Tourism Development',
    lastUpdated: new Date().toISOString(),
  },

  // 8. SOMNATH - First Jyotirlinga (Gujarat)
  {
    id: 'attr-somnath-temple',
    name: 'Shree Somnath Jyotirlinga Temple',
    category: 'First of the 12 Jyotirlingas & Coastal Monument',
    lat: 20.8880,
    lng: 70.4013,
    address: 'Somnath Mandir Road, Prabhas Patan, Veraval, Gujarat 362268',
    shortDescription: "The sacred 'Shrine Eternal', reconstructed in grand Chalukya architecture directly facing the Arabian Sea where uninterrupted ocean stretches to Antarctica.",
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=20.8880,70.4013',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free darshan; Light and Sound Show (evening) ₹30' },
    openingHours: '06:00 - 22:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 600,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Evening 19:00 for ocean sunset and Aarti',
      weatherSuitability: 'all_weather',
      crowdLevel: 'high',
    },
    photos: [
      {
        id: 'wm-st-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Somnath_temple.jpg/1280px-Somnath_temple.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Somnath_temple.jpg/400px-Somnath_temple.jpg',
        title: 'Somnath Temple silhouetted against the coastal waves',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Shree Somnath Trust',
      }
    ],
    source: 'Shree Somnath Trust',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-bhalka-tirth',
    name: 'Bhalka Tirth',
    category: 'Sacred Krishna Pilgrimage Landmark',
    lat: 20.9022,
    lng: 70.3792,
    address: 'Bhalka, Veraval-Somnath Highway, Gujarat 362265',
    shortDescription: 'Revered holy spot where Lord Krishna rested under a banyan tree before his divine departure (Dehotsarg), commemorated by a white marble temple.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=20.9022,70.3792',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free public entry' },
    openingHours: '06:00 - 21:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 45,
      walkingDistanceMeters: 300,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'medium',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or late afternoon',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-bkt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bhalka_Tirth_temple.jpg/1280px-Bhalka_Tirth_temple.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Bhalka_Tirth_temple.jpg/400px-Bhalka_Tirth_temple.jpg',
        title: 'Bhalka Tirth temple complex',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Gujarat Tourism',
      }
    ],
    source: 'Gujarat Tourism',
    lastUpdated: new Date().toISOString(),
  },

  // 9. MOUNT ABU - Dilwara Temples
  {
    id: 'attr-dilwara-temples',
    name: 'Dilwara Jain Temples',
    category: 'Marvel of Marble Inlay & Jain Architecture',
    lat: 24.6017,
    lng: 72.7233,
    address: 'Delwara, Mount Abu, Sirohi District, Rajasthan 307501',
    shortDescription: 'World-renowned 11th to 13th-century marble temples famous for peerless intricacy in translucent marble carving, domed ceilings and lotus pendants.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=24.6017,72.7233',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free admission for all visitors (cameras strictly deposited outside)' },
    openingHours: '12:00 - 17:00 Daily for tourists (Morning dedicated to devotees)',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 90,
      walkingDistanceMeters: 500,
      accessibility: 'partially_accessible',
      wheelchairSuitability: false,
      indoorOutdoor: 'indoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Afternoon 12:30 when natural light illuminates marble ceilings',
      weatherSuitability: 'indoor_safe',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-dwt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Dilwara_Temple_Ceiling_Mount_Abu.jpg/1280px-Dilwara_Temple_Ceiling_Mount_Abu.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Dilwara_Temple_Ceiling_Mount_Abu.jpg/400px-Dilwara_Temple_Ceiling_Mount_Abu.jpg',
        title: 'Intricate carved marble dome at Dilwara Temple',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Archaeological Survey of India',
      }
    ],
    source: 'Dilwara Temple Trust',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-nakki-lake-mount-abu',
    name: 'Nakki Lake & Toad Rock',
    category: 'Scenic Hill Station Lake & Rock Formations',
    lat: 24.5925,
    lng: 72.7081,
    address: 'Mount Abu, Rajasthan 307501',
    shortDescription: 'Legendary sacred lake mythologically dug with fingernails, fringed by the Aravalli hills, pedal boating, and the famous Toad Rock viewpoint.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=24.5925,72.7081',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free lake promenade; boating available from ₹100' },
    openingHours: '08:00 - 20:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 60,
      walkingDistanceMeters: 600,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'medium',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Late afternoon through sunset',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-nl-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Nakki_Lake%2C_Mount_Abu.jpg/1280px-Nakki_Lake%2C_Mount_Abu.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Nakki_Lake%2C_Mount_Abu.jpg/400px-Nakki_Lake%2C_Mount_Abu.jpg',
        title: 'Nakki Lake surrounded by Aravalli crags and forest',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Rajasthan Tourism',
      }
    ],
    source: 'Rajasthan Tourism Development',
    lastUpdated: new Date().toISOString(),
  },

  // 10. BODH GAYA - Mahabodhi Temple
  {
    id: 'attr-mahabodhi-temple',
    name: 'Mahabodhi Temple Complex & Bodhi Tree',
    category: 'UNESCO World Heritage Site & Supreme Buddhist Shrine',
    lat: 24.6960,
    lng: 84.9914,
    address: 'Bodh Gaya, Gaya District, Bihar 824231',
    shortDescription: 'Ancient 5th to 6th-century brick temple marking the sacred spot where Gautama Buddha attained supreme spiritual Enlightenment under the historic Bodhi Tree.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=24.6960,84.9914',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free UNESCO heritage entry; nominal fee for video equipment' },
    openingHours: '05:00 - 21:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 120,
      walkingDistanceMeters: 800,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'mixed',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Early morning meditation or dusk illumination',
      weatherSuitability: 'all_weather',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-mbt-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Mahabodhi_Temple_Bodh_Gaya.jpg/1280px-Mahabodhi_Temple_Bodh_Gaya.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Mahabodhi_Temple_Bodh_Gaya.jpg/400px-Mahabodhi_Temple_Bodh_Gaya.jpg',
        title: 'Pyramidal spire of the ancient Mahabodhi Temple',
        author: 'Wikimedia Commons Contributor',
        license: 'CC BY-SA 4.0',
        source: 'Bodhgaya Temple Management Committee',
      }
    ],
    source: 'Bodhgaya Temple Management Committee',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'attr-great-buddha-statue',
    name: 'Great Buddha Statue (Daibutsu)',
    category: 'Colossal Monument & Meditation Park',
    lat: 24.6983,
    lng: 84.9866,
    address: 'Temple Street, Bodh Gaya, Bihar 824231',
    shortDescription: '80-foot colossal sandstone and red granite seated Buddha statue in dhyana mudra, surrounded by 10 carved disciples in a tranquil garden.',
    directionUrl: 'https://www.google.com/maps/dir/?api=1&destination=24.6983,84.9866',
    ticketPrice: { amount: 0, currency: 'INR', pricingType: 'official', details: 'Free entrance to garden park' },
    openingHours: '07:00 - 18:00 Daily',
    taxonomy: {
      difficultyLevel: 'easy',
      estimatedDurationMinutes: 45,
      walkingDistanceMeters: 400,
      accessibility: 'verified_accessible',
      wheelchairSuitability: true,
      indoorOutdoor: 'outdoor',
      childSuitability: true,
      educationalValue: 'high',
      photographyValue: 'high',
      budgetCategory: 'budget',
      bestVisitingTime: 'Morning or late afternoon',
      weatherSuitability: 'sunny_only',
      crowdLevel: 'moderate',
    },
    photos: [
      {
        id: 'wm-gb-1',
        url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Great_Buddha_Statue_Bodhgaya.jpg/1280px-Great_Buddha_Statue_Bodhgaya.jpg',
        thumbnailUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Great_Buddha_Statue_Bodhgaya.jpg/400px-Great_Buddha_Statue_Bodhgaya.jpg',
        title: 'The 80-foot seated Great Buddha statue of Bodh Gaya',
        author: 'Wikimedia Commons',
        license: 'CC BY-SA 4.0',
        source: 'Bihar Tourism',
      }
    ],
    source: 'Daijokyo Buddhist Sect',
    lastUpdated: new Date().toISOString(),
  }
];
